commerce_nochex_gateway.commerce_payment_gateway.plugin.nochex_redirect_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'   
    language:
      type: string
      label: 'Language'
